import type { BlogPost } from "./types";

const drafts = [
  {
    slug: "hes-satin-alirken-nelere-dikkat-edilmeli", title: "HES Satın Alırken Nelere Dikkat Edilmeli?",
    description: "HES satın alma öncesinde hidrolik veri, net üretim, ekipman, bakım yatırımı ve veri odasını birlikte değerlendiren yatırımcı rehberi.",
    body: [
      { heading: "Önce yatırım sınırını tanımlayın", content: "Satın alınacak varlığın kapsamı netleşmeden teknik veri karşılaştırması yanıltıcı olabilir. Şirket hissesi ile yalnızca tesis varlıklarının satışı aynı kapsam değildir. İlk görüşmede kurulu güç, tesis sınırı, bağlantı noktası, işletme durumu ve erişilebilir kayıtlar belirlenmelidir. Yatırımcı kapasite hedefinin yanında bütçe, bölge, zamanlama ve kabul edebileceği yenileme ihtiyacını da tanımlamalıdır. Böylece teknik açıdan güçlü ancak yatırım kriterlerine uymayan projelerde gereksiz inceleme maliyeti oluşması önlenir.", links: [{ label: "Satılık HES için yatırım kriterlerinizi oluşturun", href: "/tr/satilik-hes" }] },
      { heading: "Su rejimi ile gerçekleşen üretimi ayırın", content: "Üç veya beş yıllık üretim tablosu önemli bir başlangıçtır; ancak her yılın su koşulları farklı olabilir. Sayaç kayıtları, işletme saatleri, debi ölçümleri ve kesintiler birlikte değerlendirilir. Düşük üretimin kuru yıldan mı, bakım duruşundan mı, hidrolik kısıttan mı kaynaklandığı açıklanmalıdır. Yalnızca yüksek üretimli bir yılı seçmek yerine mevcut veri döneminin uzun dönem su rejimini ne ölçüde temsil ettiği sorgulanır. Ölçülmeyen veya eksik veriler belirsizlik kaydına alınır." },
      { heading: "Ekipman raporunu bakım planına bağlayın", content: "Türbin ve jeneratörün yaşı bakım ihtiyacını tek başına açıklamaz. Titreşim trendleri, yağ analizleri, yatak sıcaklıkları, geçmiş arızalar ve yapılan revizyonlar incelenir. Su alma yapısı, iletim hattı ve cebri boru gibi yapılar da üretim sürekliliğini etkiler. Saha bulgusu için yalnızca kusur tanımı değil, gerekli test, olası duruş ve yaklaşık yatırım kapsamı kaydedilmelidir. Üretici önerileri ile işletmenin fiilen uyguladığı bakım programının tutarlılığı kontrol edilir.", links: [{ label: "Teknik due diligence kapsamını inceleyin", href: "/tr/enerji-santrali-due-diligence" }] },
      { heading: "Teknik bulguyu satın alma kararına dönüştürün", content: "Açık riskler, eksik kanıtlar ve giderilebilir kusurlar ayrı listelenir. Büyük revizyon ihtiyacı değerleme modelindeki bakım CAPEX’ine ve üretim duruşuna yansıtılır. Belirsiz bir kalemi yok saymak da aynı maliyeti iki kez düşmek de sonucu bozabilir. Rapor, kapanış öncesi çözülmesi gereken konular ile satın alma sonrasında izlenebilecek işleri ayırmalıdır. Teknik çıktı, hukuki ve mali inceleme ekiplerinin kendi değerlendirmeleriyle birlikte kullanılır.", links: [{ label: "HES değerleme parametrelerine geçin", href: "/tr/hes-degerleme" }] }
    ]
  },
  {
    slug: "ges-satin-alirken-nelere-dikkat-edilmeli", title: "GES Satın Alırken Nelere Dikkat Edilmeli?",
    description: "GES alımında lisans ve bağlantı yapısı, üretim verisi, panel-inverter durumu, arazi hakkı ve işletme giderleri için inceleme rehberi.",
    body: [
      { heading: "DC ve AC kapasiteyi aynı temelde karşılaştırın", content: "Portföy özetindeki güç değerinin panel kurulu gücünü mü, inverter gücünü mü, bağlantı kapasitesini mi anlattığını kontrol edin. Farklı ölçüm sınırları fiyat ve üretim karşılaştırmasını bozar. Ekipman envanteri, tek hat şeması ve kabul belgelerinin birbiriyle uyumlu olması gerekir. Lisanslı veya lisanssız proje niteliği, tüketim ilişkisi ve satış yapısı ayrıca kaydedilir. Başka bir tesiste kullanılan gelir modelinin bu projede de geçerli olduğu varsayılmaz.", links: [{ label: "Satılık GES kriterlerini belirleyin", href: "/tr/satilik-ges" }] },
      { heading: "Üretim kaybının kaynağını bulun", content: "Aynı döneme ait net sayaç üretimi, inverter üretimi ve ışınım ölçümleri karşılaştırılır. PR düşüklüğü; kirlenme, gölgelenme, sensör hatası, sıcaklık, arıza veya şebeke kesintisiyle ilişkili olabilir. Eksik veri bulunan günleri sessizce ortalamaya dahil etmek sonucu çarpıtır. Analiz, veri kalitesi ve dışlanan dönemleri açıklamalıdır. Uzun dönem üretim varsayımına geçerken yalnızca kısa bir testin veya tek bir yılın yeterli kanıt oluşturmadığı dikkate alınır." },
      { heading: "Panel ve inverter riskini somutlaştırın", content: "Panel seri numaraları, garanti belgeleri, inverter arıza geçmişi ve bakım kayıtları eşleştirilir. Sahada gözlenen sıcak nokta, izolasyon veya bağlantı problemi uygun test planıyla doğrulanır. İnverterin çalışıyor olması kalan proje ömrü boyunca yenileme gerektirmeyeceği anlamına gelmez. Yedek parça, servis desteği ve garanti istisnaları incelenir. Tespit edilen risk için aksiyon maliyeti, erişim gereksinimi ve üretim etkisi ayrı belirtilir.", links: [{ label: "Satın alma öncesi teknik incelemeyi planlayın", href: "/tr/enerji-santrali-due-diligence" }] },
      { heading: "Arazi ve işletme ufkunu finansal modele taşıyın", content: "Arazi mülkiyeti, kira veya çatı kullanım hakkının süresi, modelde öngörülen çalışma süresiyle tutarlı olmalıdır. Kira artışı, temizlik, güvenlik, sigorta ve inverter yenilemesi nakit akışını etkiler. Borç ve nakit tutarlarının nasıl ele alınacağı, varlık veya hisse satışı kapsamına göre belirlenir. Teknik inceleme, finansal modeldeki üretim ve yenileme varsayımlarına dayanak sağlar; tek başına işlem fiyatını kesinleştirmez.", links: [{ label: "GES değerleme yaklaşımını okuyun", href: "/tr/ges-degerleme" }] }
    ]
  },
  {
    slug: "hes-degeri-nasil-hesaplanir", title: "HES Değeri Nasıl Hesaplanır?",
    description: "Hidroelektrik santrali değerinde net üretim, gelir, gider, bakım CAPEX’i ve borcun rolü; MW çarpanının sınırları ve senaryo yaklaşımı.",
    body: [
      { heading: "MW çarpanı neden yeterli değildir?", content: "Kurulu güç, tesisin hangi kapasiteyle üretim yapabileceğini gösterir; yıl boyunca ne kadar kullanılabilir su bulunduğunu veya üretimin ne kadarının satışa dönüştüğünü söylemez. Aynı MW değerine sahip iki HES farklı düşü, debi, verim ve duruş geçmişiyle çalışabilir. Bu nedenle kapasiteye dayalı fiyat karşılaştırması yalnızca ilk kontrol niteliğindedir. Ana değerleme, doğrulanmış üretimin ve beklenen giderlerin ekonomik sonuçlarını açıklamalıdır.", links: [{ label: "HES değerleme hizmetinin kapsamı", href: "/tr/hes-degerleme" }] },
      { heading: "Gelir ve gider serisini oluşturun", content: "Net üretim tahmini, satış yapısıyla eşleştirilerek dönemsel gelir serisine çevrilir. Kaynak belirsizliği için farklı su senaryoları kullanılır. OPEX içinde personel, planlı bakım, sigorta ve diğer işletme kalemleri bulunur. Büyük revizyonlar rutin işletme giderlerine gizlenmez; bakım CAPEX’i olarak tarih ve kapsamıyla gösterilir. Vergi ve işletme sermayesi gibi mali varsayımlar ilgili uzman tarafından modele dahil edilir. Bütün tutarların para birimi ve fiyat tarihi açık olmalıdır." },
      { heading: "İşletme değeri ile özsermaye değerini ayırın", content: "Gelecek nakit akışlarının bugünkü değeri hesaplanırken kullanılan nakit akışı tanımı ile iskonto yaklaşımı tutarlı olmalıdır. Finansman öncesi proje nakit akışı ile hissedara kalan nakit akışı aynı seri değildir. Borç, nakit ve diğer işlem düzeltmeleri seçilen yönteme göre ele alınır. Böylece finansman maliyetinin veya borç tutarının iki kez hesaba katılması önlenir. Sonuç, hangi varlık ve yükümlülüklerin devredildiğini açıkça belirtmelidir." },
      { heading: "Belirsizliği senaryolarla açıklayın", content: "Üretim, satış fiyatı, büyük bakım tarihi ve iskonto varsayımı değiştirilerek sonucun hassasiyeti görülür. Kalan lisans süresi ve işletme ömrü model ufkunu sınırlar. Tek bir sonuç yerine temel, düşük ve yüksek senaryoların gerekçeleri sunulmalıdır. Eksik teknik veri varsa hangi ölçüm veya belgeyle tamamlanabileceği yazılır. Değerleme tarihi ile işlem tarihi arasındaki yeni bilgi modeli güncelleme gerektirebilir.", links: [{ label: "Teknik girdilerin doğrulanması", href: "/tr/enerji-santrali-due-diligence" }, { label: "Satılık HES yatırım süreci", href: "/tr/satilik-hes" }] }
    ]
  },
  {
    slug: "ges-degeri-nasil-hesaplanir", title: "GES Değeri Nasıl Hesaplanır?",
    description: "GES değerinde ışınım, PR, degradasyon, kullanım hakları, inverter yenilemesi ve gelecekteki nakit akışını değerlendirme yöntemi.",
    body: [
      { heading: "Üretim varsayımını teknik kanıta bağlayın", content: "GES değerlemenin temel girdisi satılabilir veya ilgili yapı içinde değerlendirilebilir net üretimdir. Üretim modeli; ışınım, sıcaklık, sistem kayıpları, kullanılabilirlik ve panel degradasyonunu içerir. Modelin geçmiş sayaç verileriyle karşılaştırılması, varsayımların gerçek işletmeyle uyumunu gösterir. Veri eksikliği veya ölçüm hatası varsa sonuç yalnızca hassas bir sayı olarak sunulmamalıdır. Kullanılan ölçüm dönemi ve dışlanan kesintiler raporda görünür olmalıdır.", links: [{ label: "GES değerleme parametreleri", href: "/tr/ges-degerleme" }] },
      { heading: "PR ve degradasyon farklı soruları cevaplar", content: "PR belirli bir dönemde sistem performansını değerlendirmeye yardımcı olur. Degradasyon ise panel performansının zaman içindeki değişimine ilişkin bir varsayımdır. Bir aylık düşük PR değerini doğrudan kalıcı panel kaybı kabul etmek hatalı olabilir. Kirlenme, gölgelenme, sensör kalibrasyonu ve inverter kesintileri ayrıca incelenmelidir. Garanti dokümanı da tek başına gerçekleşen üretimin kanıtı değildir; saha verisiyle ilişkilendirilir." },
      { heading: "Kullanım hakları ve yenilemeleri tarihlendirin", content: "Arazi kirası veya çatı kullanım hakkı modelin çalışma süresinden önce sona eriyorsa devam koşulları varsayım olarak açıklanmalıdır. İnverter yenilemesi, trafo bakımı, güvenlik ve temizlik giderleri yıllara dağıtılır. Mevcut borcun ve nakit tutarının işlemde nasıl devredileceği ayrı çalışılır. Lisans, bağlantı ve mahsuplaşma yapısındaki projeye özel unsurlar teyit edilmeden gelir devamlılığı kabul edilmez. Teknik ve mali ekipler aynı tarihli veri setini kullanmalıdır." },
      { heading: "Nakit akışını senaryolarla sınayın", content: "Üretim, gelir birim değeri, OPEX artışı ve büyük ekipman yenileme tarihi değiştirilerek değer aralığının dayanakları gösterilir. İskonto yaklaşımı, nakit akışının para birimi ve finansman kapsamıyla uyumlu olmalıdır. Değerlendirme kesin satış fiyatı taahhüdü oluşturmaz; pazarlıkta hangi varsayımın tartışıldığını netleştirir. Üretim kaybı giderilebilir bir arızadan kaynaklanıyorsa iyileştirme maliyeti ve fayda ayrı senaryoda ele alınır.", links: [{ label: "Satılık GES ön değerlendirmesi", href: "/tr/satilik-ges" }, { label: "Teknik incelemeyle veri doğrulayın", href: "/tr/enerji-santrali-due-diligence" }] }
    ]
  },
  {
    slug: "enerji-santrali-satin-alma-sureci", title: "Enerji Santrali Satın Alma Süreci",
    description: "Enerji santrali alımında kriter belirleme, gizlilik, veri odası, teknik inceleme, değerleme ve devir hazırlığının aşamaları.",
    body: [
      { heading: "Kriter belirleme ve ilk eleme", content: "Süreç, yatırımcının santral türü, kapasite aralığı, bütçe, bölge ve zamanlama hedeflerini tanımlamasıyla başlar. İşletmedeki bir varlık ile inşaat veya proje aşamasındaki yatırım aynı veri setiyle karşılaştırılmaz. İlk elemede paylaşılan özet bilgilerle temel uygunluk kontrol edilir. Üretim geçmişi, lisans durumu veya fiyat beklentisi bilinmiyorsa bu alanlar açık soru olarak kaydedilir. Bilinmeyen veri olumlu varsayımla doldurulmaz.", links: [{ label: "Yatırımcı talebi oluşturun", href: "/tr/santral-satin-al" }] },
      { heading: "Gizlilik ve veri odası erişimi", content: "İlgi somutlaştığında paylaşım sınırı, tarafların yetkisi ve gizlilik süreci netleştirilir. Veri odasında teknik, mali ve hukuki belgeler ayrı izlenir; her belgenin tarihi ve sürümü belli olmalıdır. İndirilen dosyaların kimlerle paylaşılabileceği önceden kararlaştırılır. İlk üretim tablosu ile sonradan düzeltilen kayıtların farkı açıklanır. Kontrollü erişim tarafların aynı veriye dayanmasını sağlar." },
      { heading: "İnceleme ve değerleme birlikte ilerler", content: "Teknik due diligence ekipman durumu ve üretim beklentisini doğrularken mali ve hukuki ekipler kendi kapsamlarını inceler. Büyük bakım ihtiyacı veya veri eksikliği değerleme varsayımlarına işlenir. Ön fiyat yaklaşımı yeni kanıt ortaya çıktıkça güncellenebilir. Saha ziyaretinin kapsamı erişim, işletme güvenliği ve gerekli testlere göre planlanır. Açık bulguların kimin tarafından ve hangi tarihte çözüleceği belirlenir.", links: [{ label: "Teknik due diligence süreci", href: "/tr/enerji-santrali-due-diligence" }] },
      { heading: "Devir hazırlığı ve ilk işletme dönemi", content: "İşlem koşulları ilgili uzmanlarla tamamlanırken teknik teslim listesi hazırlanır. Bakım planları, çizimler, garanti dosyaları, yedek parça envanteri ve erişim yetkileri teslim kapsamına alınır. Kritik açık işlerin kapanış öncesi çözümü veya sonrasında izlenmesi ayrı kararlaştırılır. İlk işletme dönemindeki bakım ve test öncelikleri, satın alma incelemesindeki risk kaydından türetilir. Böylece rapor uygulama planının girdisi olur.", links: [{ label: "Enerji yatırım fırsatlarına dönün", href: "/tr/satilik-enerji-santralleri" }] }
    ]
  },
  {
    slug: "santral-teknik-due-diligence-nedir", title: "Santral Teknik Due Diligence Nedir?",
    description: "Santral teknik due diligence kapsamı, veri kontrolü, saha incelemesi, üretim analizi ve risk matrisinin yatırım kararındaki rolü.",
    body: [
      { heading: "Karar sorusuna göre kapsam belirlenir", content: "Teknik due diligence, bir santralin mevcut durumunu ve gelecekteki teknik yükümlülüklerini karar amacıyla incelemektir. Satın alma, finansman veya ortaklık sürecinde farklı sorular öne çıkabilir. Kapsam tesis sınırı, erişilebilir belgeler, saha ziyareti ve planlanan testlerle tanımlanır. Bir dosya incelemesi, yapılmamış saha testlerinin yerini tutmaz. Raporda neyin görüldüğü, neyin belgelerden okunduğu ve neyin doğrulanamadığı ayrı belirtilmelidir.", links: [{ label: "Enerji santrali teknik due diligence hizmeti", href: "/tr/enerji-santrali-due-diligence" }] },
      { heading: "İşletme göstergeleri doğru sınırlarla okunur", content: "Emre amadelik tesisin kullanılabilirliğini, kapasite faktörü ise belirli dönemde üretimin kapasiteye göre düzeyini anlatır. Bu göstergeler aynı şeyi ölçmez. Şebeke kısıntısı, kaynak eksikliği ve ekipman duruşu ayrı sınıflandırılmalıdır. Yüksek kapasite faktörü tek başına ekipman sağlığının kanıtı değildir. İnceleme ölçüm dönemini ve hesaplama sınırını açıklar; göstergeleri alarm, bakım ve üretim kayıtlarıyla ilişkilendirir." },
      { heading: "Saha bulgusu kanıtla desteklenir", content: "Fotoğraf, test kaydı, işletme trendi ve bakım dokümanı aynı bulgu altında ilişkilendirilir. Tekrarlayan alarmın kök nedeni belirlenememişse bu belirsizlik raporda korunur. Kusurun etkisi güvenlik, üretim, şebeke uyumu veya bakım maliyeti açısından değerlendirilir. Ek test gerektiğinde test amacı, duruş gereksinimi ve sorumlusu yazılır. Böylece genel bir kontrol listesi yerine yatırımcının aksiyon alabileceği kanıt seti oluşur." },
      { heading: "Sonuç risk matrisi ve aksiyon planıdır", content: "Risk matrisi, olasılık ve etkinin yanında maliyet aralığı, zamanlama ve giderilme koşullarını içerir. Kritik bulgunun yalnızca renkle işaretlenmesi yeterli değildir; işlem öncesinde nasıl doğrulanacağı da belirtilmelidir. Teknik yatırım raporu hukuki ve mali incelemenin yerine geçmez. Onların kullanacağı üretim ve CAPEX varsayımlarını destekler. Satın alma sonrası bakım planı da aynı bulgular üzerinden geliştirilebilir.", links: [{ label: "Santral satın alma talebinizi paylaşın", href: "/tr/santral-satin-al" }, { label: "Yatırım fırsatlarını inceleyin", href: "/tr/satilik-enerji-santralleri" }] }
    ]
  },
  {
    slug: "enerji-santrali-satarken-nelere-dikkat-edilmeli", title: "Enerji Santrali Satarken Nelere Dikkat Edilmeli?",
    description: "Santral satışında veri hazırlığı, gizlilik, fiyat beklentisi, teknik risklerin açıklanması ve yatırımcı incelemesinin yönetimi.",
    body: [
      { heading: "Satış kapsamını ve veri sorumlusunu belirleyin", content: "Varlık satışı ile şirket hissesi satışı farklı belge ve yükümlülük kapsamlarına sahip olabilir. Önce hangi tesislerin, hakların ve sözleşmelerin görüşmeye dahil olduğu netleştirilir. Veri taleplerini yönetecek tek sorumlu belirlemek, farklı yatırımcılara çelişkili tablolar gönderilmesini önler. Üretim, bakım ve ekipman envanterinin güncel sürümü hazırlanır. Eksik kayıtların ne zaman sağlanabileceği açıklanır; verinin varmış gibi sunulması sonraki aşamalarda güven kaybına yol açar.", links: [{ label: "Santral satış talebi oluşturun", href: "/tr/santralini-sat" }] },
      { heading: "Gizli satışta ilk özetin sınırını koruyun", content: "Anonim tanıtımın amacı varlığı ifşa etmeden temel uygunluğu değerlendirmektir. Santral veya şirket adı kadar serbest metin, dosya adı ve kesin konum da kimliği açığa çıkarabilir. İlk aşamada bölge, teknoloji ve paylaşılmasına izin verilen teknik özet kullanılır. Daha ayrıntılı veri için yatırımcı yeterliliği ve gizlilik süreci tamamlanır. Satıcının bilgisi dışında açık ilana dönüşen başvuru akışı kullanılmamalıdır." },
      { heading: "Fiyat beklentisini kanıtlarla destekleyin", content: "Satış fiyatını yalnızca kurulu güç üzerinden açıklamak yerine net üretim, gelir yapısı ve gider geçmişini hazırlayın. Büyük bakım veya ekipman yenilemesi gerektiren kalemleri kapsam ve takvimleriyle sunmak incelemeyi kolaylaştırır. Finansman yükümlülükleri ilgili mali uzmanla kontrol edilir. Değerleme yaklaşımı, varlık değeri ile hissedarın elde edeceği tutarı ayırmalıdır. Fiyat beklentisi ile doğrulanmış değerleme sonucu aynı kavram değildir.", links: [{ label: "HES değerleme", href: "/tr/hes-degerleme" }, { label: "GES değerleme", href: "/tr/ges-degerleme" }] },
      { heading: "İnceleme takvimini işletmeyle koordine edin", content: "Yatırımcı saha ziyaretleri güvenlik ve işletme programıyla birlikte planlanır. Test için duruş gerekiyorsa kapsam ve maliyet önceden konuşulur. Sorulara verilen yanıtlar veri odasında sürüm takibiyle saklanır. Satış sürecinde meydana gelen yeni arıza veya önemli bakım, önceki teknik özeti güncelleme gerektirebilir. Teknik teslim listesi erken hazırlanırsa kapanış aşamasında belge ve envanter eksikliği daha az sürpriz yaratır.", links: [{ label: "Enerji yatırım platformu", href: "/tr/satilik-enerji-santralleri" }] }
    ]
  },
  {
    slug: "hes-satis-sureci-nasil-yonetilir", title: "HES Satış Süreci Nasıl Yönetilir?",
    description: "HES satışında hidrolik ve üretim kayıtlarının hazırlanması, anonim portföy paylaşımı, teknik inceleme ve kontrollü devir planı.",
    body: [
      { heading: "Hidrolik ve üretim dosyasını düzenleyin", content: "HES satış hazırlığında sayaç üretimi, debi kayıtları, işletme saatleri ve duruş açıklamaları ortak dönem tablosunda toplanır. Hidrolik koşulların değiştiği yıllar belirtilir. Kapasite, türbin adedi, net düşü ve ana ekipman envanteri güncel teknik belgelerle eşleştirilir. Üretim kayıtlarında revizyon varsa ilk veriyle farkı açıklanır. Yatırımcıya sunulan özetin her önemli rakamı kontrollü veri odasındaki bir kayda bağlanabilmelidir.", links: [{ label: "Satılık HES ve yatırımcı kriterleri", href: "/tr/satilik-hes" }] },
      { heading: "Paylaşımı kademeli yönetin", content: "İlk temas için anonim teknik özet hazırlanır. Yatırımcının kapasite, bütçe ve zamanlama kriterleri bu özetle karşılaştırılır. İlgi uygun bulunduğunda yetki ve gizlilik süreci tamamlanır; ayrıntılı teknik ve mali belgeler kontrollü erişimle açılır. Dosyalardaki santral adı, koordinat ve şirket bilgileri de paylaşım kapsamına dahildir. Sadece kart başlığını gizlemek, belgenin içeriği kimliği açıklıyorsa yeterli değildir." },
      { heading: "Teknik bulguları görüşmelerden önce sıralayın", content: "Türbin-jeneratör bakımı, cebri boru durumu, su yapıları ve şebeke bağlantısına ilişkin açık işler kaydedilir. Çözülmüş arıza ile tekrar eden problem ayrı gösterilir. Yakın vadeli revizyonların maliyeti ve üretim duruşu değerleme modeline aktarılır. Satıcı ön incelemesi yatırımcının incelemesini ortadan kaldırmaz; yanıtların kanıtla hazırlanmasını sağlar. Her açık bulgu için mevcut belge, eksik test ve önerilen sonraki adım belirtilir.", links: [{ label: "HES değerleme parametreleri", href: "/tr/hes-degerleme" }, { label: "Teknik due diligence", href: "/tr/enerji-santrali-due-diligence" }] },
      { heading: "Teslimi işletme sürekliliğiyle birlikte planlayın", content: "Son aşamada ekipman, yedek parça, bakım kayıtları, erişim yetkileri ve çizimler teslim listesine alınır. Su ve üretim yönetimi için kritik işletme bilgileri kaybolmamalıdır. Açık teknik işlerin devirden önce mi sonra mı tamamlanacağı ekiplerle belirlenir. İşlemdeki hukuki ve mali koşullar kendi uzmanlarının sorumluluğunda yürütülür. Teknik danışmanlık karar ve teslimin doğrulanabilir veriyle desteklenmesine odaklanır.", links: [{ label: "Gizli HES satış talebi oluşturun", href: "/tr/santralini-sat?type=HES" }] }
    ]
  }
];

export const investmentArticles: BlogPost[] = drafts.map((draft, index) => ({
  ...draft, category: "Enerji Yatırımları", categorySlug: "enerji-yatirimlari",
  date: "2026-09-06", readingTime: "4 dk", author: "Bünyamin Öztoprak",
  toc: draft.body.map((section) => section.heading), serviceLinks: ["yenilenebilir-enerji-yatirim-danismanligi", "teknik-durum-tespiti"],
  related: [drafts[(index + 1) % drafts.length].slug, drafts[(index + 4) % drafts.length].slug]
}));
