import type { Locale } from "@/lib/i18n";
import type { Project } from "@/content/types";

export const projects: Record<Locale, Project[]> = {
  en: [
    {
      slug: "hydropower-portfolio-optimization",
      title: "Hydropower Portfolio Optimization",
      category: "Hydropower projects",
      capacity: "118 MW",
      location: "Turkey",
      type: "Hydropower",
      role: "Technical consultant",
      summary: "Operational review and performance improvement roadmap for a multi-unit hydropower portfolio.",
      scope: ["Generation loss analysis", "Maintenance routine review", "Turbine-generator reliability observations", "Owner reporting"],
      commissioning: "Reviewed historical commissioning evidence and identified documentation gaps affecting long-term reliability tracking.",
      om: "Analyzed outage patterns, availability drivers and maintenance planning discipline.",
      results: ["Prioritized O&M actions", "Improved visibility on generation losses", "Clear investment ranking for corrective works"]
    },
    {
      slug: "solar-plant-performance-recovery",
      title: "Solar Plant Performance Recovery",
      category: "Solar power projects",
      capacity: "46 MW",
      location: "Central Anatolia",
      type: "Solar PV",
      role: "Performance advisor",
      summary: "Technical review of underperforming solar assets with EPC quality and O&M action planning.",
      scope: ["PR review", "Inverter and string-level observations", "O&M procedure review", "Corrective action roadmap"],
      commissioning: "Assessed test records and handover completeness to separate EPC defects from operational degradation.",
      om: "Reviewed cleaning, inspection and response routines against production losses.",
      results: ["Underperformance causes grouped by impact", "O&M improvement plan", "Owner-ready reporting package"]
    },
    {
      slug: "commissioning-readiness-program",
      title: "Power Plant Commissioning Readiness Program",
      category: "Commissioning experience",
      capacity: "72 MW",
      location: "Turkey",
      type: "Renewable power plant",
      role: "Commissioning consultant",
      summary: "Commissioning readiness support for a renewable energy asset approaching first energization and performance testing.",
      scope: ["Commissioning checklist", "Test procedure challenge review", "Punch-list structure", "Handover documentation"],
      commissioning: "Built a staged readiness view covering mechanical completion, electrical energization, functional tests and performance tests.",
      om: "Connected commissioning evidence to future operating procedures and maintenance baselines.",
      results: ["Reduced startup uncertainty", "Clear test ownership", "Improved handover quality"]
    },
    {
      slug: "existing-plant-technical-audit",
      title: "Existing Power Plant Technical Audit",
      category: "Technical audit experience",
      capacity: "38 MW",
      location: "Turkey",
      type: "Hydropower and balance of plant",
      role: "Independent technical auditor",
      summary: "Technical audit for an operating power plant supporting asset health, investment planning and risk prioritization.",
      scope: ["Site inspection", "Document and drawing review", "Protection observations", "O&M maturity review"],
      commissioning: "Compared commissioning records with present-day operating evidence and recurring events.",
      om: "Reviewed spare parts, maintenance planning, fault history and availability tracking.",
      results: ["Asset health risk register", "CAPEX prioritization input", "Board-level technical summary"]
    },
    {
      slug: "hydropower-commissioning-case-study",
      title: "Hydropower Commissioning Case Study",
      category: "Commissioning case study",
      capacity: "64 MW",
      location: "Anonymized international HPP",
      type: "Hydropower",
      role: "Commissioning and owner-side technical advisor",
      summary: "Anonymized hydropower commissioning review focused on readiness, test evidence, punch-list control and operational handover.",
      scope: ["Commissioning readiness review", "Protection and energization evidence", "Functional test sequence review", "Punch-list prioritization"],
      commissioning: "Reviewed energization prerequisites, test procedures, acceptance criteria and handover evidence before performance testing.",
      om: "Connected commissioning records to future operating routines, alarm response and maintenance baseline requirements.",
      challenge: "The owner needed confidence that the plant could move from construction completion to controlled startup without carrying unresolved technical risk into commercial operation.",
      approach: "The review separated construction completion, pre-commissioning, energization, functional testing and performance testing into evidence-based gates.",
      actions: ["Challenged commissioning procedure completeness", "Ranked punch-list items by startup risk", "Reviewed protection and control readiness", "Defined handover evidence required by operations"],
      results: ["Reduced startup uncertainty", "Improved test ownership", "Clearer operational handover package"],
      lessons: ["Commissioning must be planned before energization pressure rises", "Punch-list items should be ranked by operational risk, not only by discipline", "Handover evidence is an O&M reliability asset"]
    },
    {
      slug: "plant-performance-improvement-case-study",
      title: "Plant Performance Improvement Case Study",
      category: "O&M optimization case study",
      capacity: "92 MW",
      location: "Anonymized renewable portfolio",
      type: "Hydropower and solar operations",
      role: "Performance improvement consultant",
      summary: "Anonymized performance improvement review connecting outage history, alarms, O&M discipline and generation loss to corrective actions.",
      scope: ["Generation loss assessment", "Availability and outage review", "Maintenance planning review", "Corrective action roadmap"],
      commissioning: "Compared historical test baselines with present operating patterns to identify deterioration and documentation gaps.",
      om: "Reviewed alarm discipline, recurring failures, spare parts planning and operator response routines.",
      challenge: "The owner had production losses but limited clarity on which losses were unavoidable, which were technical, and which required CAPEX.",
      approach: "The analysis grouped losses by equipment, operations, grid interface, water/resource conditions and maintenance response.",
      actions: ["Built loss categories from operating data", "Reviewed outage and alarm history", "Prioritized actions by energy impact", "Created a staged O&M improvement roadmap"],
      results: ["Clear generation recovery priorities", "Better maintenance planning discipline", "Owner-ready performance improvement plan"],
      lessons: ["Performance reviews need operating context", "Availability alone is not enough to explain lost value", "Corrective actions should be ranked by energy impact and execution risk"]
    },
    {
      slug: "solar-plant-technical-audit-case-study",
      title: "Solar Plant Technical Audit Case Study",
      category: "Solar audit case study",
      capacity: "48 MWp",
      location: "Anonymized solar PV asset",
      type: "Solar PV",
      role: "Independent solar technical auditor",
      summary: "Anonymized solar plant technical audit covering PR analysis, EPC quality evidence, inverter behavior and O&M response.",
      scope: ["Performance ratio review", "Inverter and string observations", "EPC handover evidence", "O&M routine review"],
      commissioning: "Reviewed commissioning and handover records to distinguish delivery defects from operational degradation.",
      om: "Assessed inspection routines, cleaning logic, response time and recurring availability issues.",
      challenge: "The asset showed underperformance, but the owner needed to separate resource variation from technical losses and EPC-related quality concerns.",
      approach: "The audit combined production data, field observations, inverter-level behavior and handover evidence into one technical risk view.",
      actions: ["Separated irradiance and curtailment effects from technical loss", "Reviewed inverter availability patterns", "Checked EPC evidence quality", "Defined O&M response improvements"],
      results: ["Clear PR loss diagnosis", "Prioritized recovery actions", "Improved owner visibility on EPC and O&M responsibilities"],
      lessons: ["Solar audits should not rely on PR alone", "EPC evidence is essential for accountability", "Fast O&M response loops protect long-term yield"]
    },
    {
      slug: "epc-owner-side-technical-control-case-study",
      title: "EPC Owner-Side Technical Control Case Study",
      category: "Owner's engineering case study",
      capacity: "71 MW",
      location: "Anonymized EPC project",
      type: "Renewable power plant",
      role: "Owner-side EPC technical advisor",
      summary: "Anonymized EPC owner-side technical control case study focused on design interfaces, contractor deliverables, commissioning readiness and risk reporting.",
      scope: ["EPC interface review", "Contractor deliverable challenge", "Technical risk register", "Commissioning readiness support"],
      commissioning: "Reviewed readiness gates and acceptance criteria before energization and performance testing.",
      om: "Checked whether EPC deliverables could support long-term operation, maintenance planning and asset documentation.",
      challenge: "The owner needed independent technical visibility while multiple EPC workstreams were converging toward commissioning.",
      approach: "The advisory work created a structured view of interface risks, open technical decisions, deliverable gaps and owner approvals.",
      actions: ["Reviewed technical deliverables", "Mapped interface ownership", "Prepared owner decision memos", "Tracked commissioning readiness risks"],
      results: ["Improved owner control", "Reduced ambiguity in EPC interfaces", "Stronger handover and commissioning discipline"],
      lessons: ["Owner-side control must start before commissioning", "Interface risk is a major driver of EPC delay", "Decision memos help owners act without slowing delivery"]
    }
  ],
  tr: [
    {
      slug: "hes-portfoy-optimizasyonu",
      title: "HES Portföy Optimizasyonu",
      category: "HES projeleri",
      capacity: "118 MW",
      location: "Türkiye",
      type: "Hidroelektrik",
      role: "Teknik danışman",
      summary: "Çok üniteli HES portföyü için operasyonel inceleme ve performans iyileştirme yol haritası.",
      scope: ["Üretim kaybı analizi", "Bakım rutinleri incelemesi", "Türbin-jeneratör güvenilirlik gözlemleri", "İşveren raporlaması"],
      commissioning: "Geçmiş devreye alma kanıtları incelendi ve uzun vadeli güvenilirlik takibini etkileyen dokümantasyon boşlukları belirlendi.",
      om: "Duruş paternleri, emre amadelik sürücüleri ve bakım planlama disiplini analiz edildi.",
      results: ["Öncelikli O&M aksiyonları", "Üretim kayıplarında daha net görünürlük", "Düzeltici işler için yatırım sıralaması"]
    },
    {
      slug: "ges-performans-toparlama",
      title: "GES Performans Toparlama",
      category: "GES projeleri",
      capacity: "46 MW",
      location: "İç Anadolu",
      type: "Güneş PV",
      role: "Performans danışmanı",
      summary: "Düşük performans gösteren GES varlıkları için EPC kalite ve O&M aksiyon planlaması odaklı teknik inceleme.",
      scope: ["PR incelemesi", "İnverter ve string düzeyi gözlemler", "O&M prosedür incelemesi", "Düzeltici aksiyon yol haritası"],
      commissioning: "EPC kusurlarını operasyonel bozulmadan ayırmak için test kayıtları ve teslim eksiksizliği değerlendirildi.",
      om: "Temizlik, kontrol ve müdahale rutinleri üretim kayıpları ile karşılaştırıldı.",
      results: ["Düşük performans nedenleri etkiye göre gruplandı", "O&M iyileştirme planı", "İşveren için raporlama paketi"]
    },
    {
      slug: "devreye-alma-hazirlik-programi",
      title: "Enerji Santrali Devreye Alma Hazırlık Programı",
      category: "Devreye alma deneyimi",
      capacity: "72 MW",
      location: "Türkiye",
      type: "Yenilenebilir enerji santrali",
      role: "Devreye alma danışmanı",
      summary: "İlk enerjilendirme ve performans testlerine yaklaşan yenilenebilir enerji varlığı için devreye alma hazırlık desteği.",
      scope: ["Devreye alma kontrol listesi", "Test prosedürü teknik inceleme", "Eksik iş yapısı", "Teslim dokümantasyonu"],
      commissioning: "Mekanik tamamlama, elektrik enerjilendirme, fonksiyonel testler ve performans testlerini kapsayan aşamalı hazırlık görünümü oluşturuldu.",
      om: "Devreye alma kanıtları gelecekteki işletme prosedürleri ve bakım bazları ile ilişkilendirildi.",
      results: ["Başlangıç belirsizliği azaltıldı", "Test sorumlulukları netleşti", "Teslim kalitesi iyileştirildi"]
    },
    {
      slug: "mevcut-santral-teknik-denetim",
      title: "Mevcut Enerji Santrali Teknik Denetimi",
      category: "Teknik denetim deneyimi",
      capacity: "38 MW",
      location: "Türkiye",
      type: "HES ve yardımcı sistemler",
      role: "Bağımsız teknik denetçi",
      summary: "Varlık sağlığı, yatırım planlaması ve risk önceliklendirmesi için çalışan santralde teknik denetim.",
      scope: ["Saha incelemesi", "Doküman ve çizim incelemesi", "Koruma gözlemleri", "O&M olgunluk incelemesi"],
      commissioning: "Devreye alma kayıtları mevcut işletme kanıtları ve tekrarlayan olaylarla karşılaştırıldı.",
      om: "Yedek parça, bakım planlama, arıza geçmişi ve emre amadelik takibi incelendi.",
      results: ["Varlık sağlığı risk listesi", "CAPEX önceliklendirme girdisi", "Yönetim düzeyi teknik özet"]
    },
    {
      slug: "hes-devreye-alma-vaka-calismasi",
      title: "HES Devreye Alma Vaka Çalışması",
      category: "Devreye alma vaka çalışması",
      capacity: "64 MW",
      location: "Anonim uluslararası HES",
      type: "Hidroelektrik",
      role: "Devreye alma ve işveren tarafı teknik danışman",
      summary: "Hazırlık, test kanıtı, eksik iş kontrolü ve işletmeye teslim odaklı anonim HES devreye alma incelemesi.",
      scope: ["Devreye alma hazırlık incelemesi", "Koruma ve enerjilendirme kanıtı", "Fonksiyonel test sırası incelemesi", "Eksik iş önceliklendirme"],
      commissioning: "Performans testleri öncesinde enerjilendirme ön koşulları, test prosedürleri, kabul kriterleri ve teslim kanıtları incelendi.",
      om: "Devreye alma kayıtları gelecekteki işletme rutinleri, alarm müdahalesi ve bakım bazlarıyla ilişkilendirildi.",
      challenge: "İşveren, santralin ticari işletmeye teknik risk taşımadan kontrollü başlangıca geçebileceğinden emin olmak istiyordu.",
      approach: "İnceleme inşaat tamamlama, ön devreye alma, enerjilendirme, fonksiyonel test ve performans testlerini kanıta dayalı kapılara ayırdı.",
      actions: ["Devreye alma prosedürleri sorgulandı", "Eksik işler başlangıç riskine göre sıralandı", "Koruma ve kontrol hazırlığı incelendi", "İşletme teslim kanıtları tanımlandı"],
      results: ["Başlangıç belirsizliği azaltıldı", "Test sahipliği netleşti", "İşletmeye teslim paketi güçlendi"],
      lessons: ["Devreye alma enerjilendirme baskısı oluşmadan planlanmalıdır", "Eksik işler disipline değil işletme riskine göre sıralanmalıdır", "Teslim kanıtı O&M güvenilirlik varlığıdır"]
    },
    {
      slug: "santral-performans-iyilestirme-vaka-calismasi",
      title: "Santral Performans İyileştirme Vaka Çalışması",
      category: "O&M optimizasyon vaka çalışması",
      capacity: "92 MW",
      location: "Anonim yenilenebilir portföy",
      type: "HES ve GES işletme",
      role: "Performans iyileştirme danışmanı",
      summary: "Duruş geçmişi, alarmlar, O&M disiplini ve üretim kaybını düzeltici aksiyonlara bağlayan anonim performans iyileştirme incelemesi.",
      scope: ["Üretim kaybı değerlendirmesi", "Emre amadelik ve duruş incelemesi", "Bakım planlama incelemesi", "Düzeltici aksiyon yol haritası"],
      commissioning: "Geçmiş test bazları mevcut işletme paternleriyle karşılaştırılarak bozulma ve dokümantasyon boşlukları belirlendi.",
      om: "Alarm disiplini, tekrarlayan arızalar, yedek parça planlama ve operatör müdahale rutinleri incelendi.",
      challenge: "İşveren üretim kayıplarının hangilerinin kaçınılmaz, teknik veya CAPEX gerektiren kayıp olduğunu netleştirmek istiyordu.",
      approach: "Analiz kayıpları ekipman, işletme, şebeke arayüzü, kaynak koşulları ve bakım müdahalesi başlıklarına ayırdı.",
      actions: ["İşletme verisinden kayıp kategorileri oluşturuldu", "Duruş ve alarm geçmişi incelendi", "Aksiyonlar enerji etkisine göre sıralandı", "Aşamalı O&M iyileştirme yol haritası hazırlandı"],
      results: ["Net üretim toparlama öncelikleri", "Daha iyi bakım planlama disiplini", "İşveren için performans iyileştirme planı"],
      lessons: ["Performans incelemesi işletme bağlamı ister", "Emre amadelik tek başına değer kaybını açıklamaz", "Düzeltici aksiyonlar enerji etkisi ve uygulama riskine göre sıralanmalıdır"]
    },
    {
      slug: "ges-teknik-denetim-vaka-calismasi",
      title: "GES Teknik Denetim Vaka Çalışması",
      category: "GES denetim vaka çalışması",
      capacity: "48 MWp",
      location: "Anonim GES varlığı",
      type: "Güneş PV",
      role: "Bağımsız GES teknik denetçisi",
      summary: "PR analizi, EPC kalite kanıtı, inverter davranışı ve O&M müdahalesini kapsayan anonim GES teknik denetimi.",
      scope: ["Performans oranı incelemesi", "İnverter ve string gözlemleri", "EPC teslim kanıtı", "O&M rutin incelemesi"],
      commissioning: "Düşük performansın teslim kusuru mu işletme bozulması mı olduğunu ayırmak için devreye alma ve teslim kayıtları incelendi.",
      om: "Kontrol rutinleri, temizlik mantığı, müdahale süresi ve tekrarlayan emre amadelik sorunları değerlendirildi.",
      challenge: "Varlık düşük performans gösteriyordu; işveren kaynak değişkenliği ile teknik kayıpları ve EPC kalite konularını ayırmak istiyordu.",
      approach: "Denetim üretim verisi, saha gözlemleri, inverter davranışı ve teslim kanıtını tek teknik risk görünümünde birleştirdi.",
      actions: ["Işınım ve kısıt etkileri teknik kayıptan ayrıldı", "İnverter emre amadelik paternleri incelendi", "EPC kanıt kalitesi kontrol edildi", "O&M müdahale iyileştirmeleri tanımlandı"],
      results: ["Net PR kayıp teşhisi", "Öncelikli toparlama aksiyonları", "EPC ve O&M sorumluluklarında daha iyi görünürlük"],
      lessons: ["GES denetimi yalnızca PR'a dayanmamalıdır", "EPC kanıtı sorumluluk için kritiktir", "Hızlı O&M müdahale döngüleri uzun vadeli üretimi korur"]
    },
    {
      slug: "epc-isveren-tarafi-teknik-kontrol-vaka-calismasi",
      title: "EPC İşveren Tarafı Teknik Kontrol Vaka Çalışması",
      category: "İşveren mühendisliği vaka çalışması",
      capacity: "71 MW",
      location: "Anonim EPC projesi",
      type: "Yenilenebilir enerji santrali",
      role: "İşveren tarafı EPC teknik danışmanı",
      summary: "Tasarım arayüzleri, yüklenici çıktıları, devreye alma hazırlığı ve risk raporlamasına odaklanan anonim EPC işveren tarafı teknik kontrol vaka çalışması.",
      scope: ["EPC arayüz incelemesi", "Yüklenici doküman sorgulaması", "Teknik risk listesi", "Devreye alma hazırlık desteği"],
      commissioning: "Enerjilendirme ve performans testleri öncesinde hazırlık kapıları ve kabul kriterleri incelendi.",
      om: "EPC çıktılarının uzun vadeli işletme, bakım planlama ve varlık dokümantasyonunu destekleyip desteklemediği kontrol edildi.",
      challenge: "İşveren, birden fazla EPC iş akışı devreye alma aşamasına yaklaşırken bağımsız teknik görünürlük istiyordu.",
      approach: "Danışmanlık arayüz riskleri, açık teknik kararlar, doküman boşlukları ve işveren onayları için yapılandırılmış görünüm oluşturdu.",
      actions: ["Teknik çıktılar incelendi", "Arayüz sahipliği haritalandı", "İşveren karar notları hazırlandı", "Devreye alma hazırlık riskleri takip edildi"],
      results: ["İşveren kontrolü güçlendi", "EPC arayüz belirsizliği azaldı", "Teslim ve devreye alma disiplini güçlendi"],
      lessons: ["İşveren tarafı kontrol devreye almadan önce başlamalıdır", "Arayüz riski EPC gecikmesinin önemli nedenidir", "Karar notları teslimi yavaşlatmadan işverenin aksiyon almasını sağlar"]
    }
  ]
};

export function getProjects(locale: Locale) {
  return projects[locale];
}

export function getProject(locale: Locale, slug: string) {
  return projects[locale].find((project) => project.slug === slug);
}
